services:
  postgres:
    image: postgres:16
    container_name: fintrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fintrack_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - fintrack_pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fintrack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fintrack_pgdata: